accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('enter/', auth_views.LoginView.as_view(
        extra_context={'user_count':User.objects.all().count()}
    ), name='login'),
    path('', login_required(views.HomePage.as_view()), name='home'),
    path('<slug:username>/create-profile/', login_required(views.CreateProfile.as_view()), name='create_profile'),
	path('<slug:username>/', login_required(views.DetailProfile.as_view()), name='detail_profile'),
	path('<slug:username>/edit-profile/',login_required(views.UpdateProfile.as_view()), name='update_profile'),
	path('follow/<slug:username>/', login_required(views.follow))
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/' , include('social_django.urls', namespace='social')),
    path('', include('posts.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from io import BytesIO
from PIL import Image
from django.core.files import File
import requests
from threading import Thread
from posts import models as post_models

def compress(image):
    im = Image.open(image)
    if im.mode in ("RGBA","P"):
    	im = im.convert("RGB")
    im_io = BytesIO()
    im = im.resize((150,150))
    im.save(im_io, 'JPEG', quality=60)
    new_image = File(im_io, name=image.name)
    return new_image

class Profile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=80)
	email = models.EmailField()
	location = models.CharField(max_length=255)
	profile_picture = models.ImageField(upload_to='media/images/profile_picture', max_length=500)
	bio = models.TextField()
	website = models.URLField(blank=True)
	followers = models.ManyToManyField('Profile',related_name='followed_by')
	following = models.ManyToManyField('Profile')
	gitlab_url = models.URLField(blank=True)
	behance_url = models.URLField(blank=True)
	instagram_url = models.URLField(blank=True)
	github_url = models.URLField(blank=True)
	def __str__(self):
		return str(self.user.username)

	def save(self, *args, **kwargs):
		t = Thread(target=GithubTask(self.user))
		t.start()
		self.profile_picture = compress(self.profile_picture)
		super().save(*args, **kwargs)

	def get_post_count(self):
		posts = post_models.Post.objects.filter(author=self.user)
		return posts.count()

class GitHubRepo(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	description = models.TextField(blank=True)
	top_language = models.CharField(max_length=255,blank=True)
	stars = models.IntegerField(blank=True)
	fork = models.BooleanField(default=False)
	url = models.URLField(blank=True)
	def __str__(self) -> str:
		return str(self.name)

class GitHubProfile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	repos = models.ManyToManyField(GitHubRepo)

	def __str__(self) -> str:
		return str(self.user)


def GithubTask(user):
	r = requests.get(f'https://gh-pinned-repos-5l2i19um3.vercel.app/?username={user}')
	response = r.json()
	gh = GitHubProfile.objects.filter(user=user)
	if not gh.exists():
		for i in response:
			name = i['repo']
			description = i['description']
			try:
				language = i['language']
			except KeyError:
				language = ''
			stars = i['stars']
			url = i['link']
			gh_repo = GitHubRepo(user=user,
				name=name,
				description=description,
				top_language=language,
				stars=stars,
				fork=False,
				url=url
			)
			gh_repo.save()
		gh_profile = GitHubProfile(user=user)
		gh_profile.save()
		gh_repos = GitHubRepo.objects.filter(user=user)
		for i in gh_repos:
			gh_profile.repos.add(i)
			gh_profile.save()

		for i in gh_repos:
			req = requests.get(f'https://api.github.com/repos/{i.user.username}/{i.name}')
			res = req.json()
			if res['fork'] == True:
				i.fork = True
				i.save()

accounts/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['profile_picture'].required = False
	class Meta:
		model = Profile
		fields = ['name', 'email', 'bio', 'location', 'profile_picture', 'website',
		'gitlab_url','behance_url','instagram_url','github_url']

accounts/views.py
from django.core.files.base import ContentFile
from django.http.response import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from accounts.forms import ProfileForm
from django.views.generic.edit import CreateView
from accounts.models import GitHubProfile, Profile
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views.generic import View
from posts.models import Post

import base64

class HomePage(View):
	def get(self, request, *args, **kwargs):
		p = Profile.objects.filter(
		    user=User.objects.get(username=request.user.username))
		if not p.exists():
			return redirect('create_profile', username=request.user.username)
		return render(request, "homepage.html", {"profile":p[0]})


class CreateProfile(CreateView):
	model = Profile
	fields = ['name', 'email', 'bio', 'location', 'profile_picture', 'website', 'gitlab_url','github_url','instagram_url','behance_url']

	def get(self, request, *args, **kwargs):
		if request.user.username != self.kwargs['username']:
			return redirect('home')
		p = Profile.objects.filter(user=User.objects.get(username=request.user))
		if p.exists():
			return redirect('update_profile', username=request.user.username)
		
		else:
			return super().get(request, *args, **kwargs)

	def form_valid(self, form):
		name = self.request.POST.get('name')
		email = self.request.POST.get('email')
		bio = self.request.POST.get('bio')
		location = self.request.POST.get('location')
		profile_picture = self.request.FILES['profile_picture']
		website = self.request.POST.get('website')
		user = User.objects.get(username=self.request.user.username)
		gitlab_url = self.request.POST.get('gitlab_url')
		instagram_url = self.request.POST.get('instagram_url')
		github_url = self.request.POST.get('github_url')
		behance_url = self.request.POST.get('behance_url')
		p = Profile(name=name, email=email, bio=bio, location=location,
		user=user,profile_picture=profile_picture,website=website, github_url=github_url,
		gitlab_url=gitlab_url,instagram_url=instagram_url,behance_url=behance_url)
		p.save()
		print(p)
		return redirect("detail_profile", username=user.username)

class UpdateProfile(View):
	def get(self, request, *args, **kwargs):
		if request.user.username != self.kwargs['username']:
			return redirect('home')
		else:
			form = ProfileForm()
			profile = Profile.objects.get(user=User.objects.get(username=self.request.user))
			return render(request, "accounts/update_profile_form.html", {"form":form, "profile":profile})

	def post(self, request, *args, **kwargs):
		form = ProfileForm(self.request.POST, self.request.FILES)
		if form.is_valid():
			name = self.request.POST.get('name')
			email = self.request.POST.get('email')
			bio = self.request.POST.get('bio')
			location = self.request.POST.get('location')
			website = self.request.POST.get('website')
			gitlab_url = self.request.POST.get('gitlab_url')
			instagram_url = self.request.POST.get('instagram_url')
			github_url = self.request.POST.get('github_url')
			behance_url = self.request.POST.get('behance_url')

			user = User.objects.get(username=self.request.user.username)
			p = Profile.objects.get(user=User.objects.get(username=request.user))
			p.name = name
			p.email = email
			p.bio = bio
			p.location = location
			p.website = website
			p.gitlab_url = gitlab_url
			p.github_url = github_url
			p.instagram_url = instagram_url
			p.behance_url = behance_url
			p.save()
			try:
				profile_picture = self.request.FILES['profile_picture']
				base_64_profile = False
				if profile_picture == None:
					profile_picture = self.request.POST.get('profile_base64')
					base_64_profile = True
				if base_64_profile:
					format, imgstr = profile_picture.split(';base64,')
					ext = format.split('/')[-1]
					data = ContentFile(base64.b64decode(imgstr), name=f"{user.username}." + ext)
					p.profile_picture.save(f"{user.username}.ext", data, save=True)
					p.save()
				else:
					p.profile_picture = profile_picture
					p.save()
			except MultiValueDictKeyError:
				return redirect("detail_profile", username=user.username)
			return redirect("detail_profile", username=user.username)
		else:
			profile = Profile.objects.get(user=User.objects.get(username=self.request.user))
			return render(request, "accounts/update_profile_form.html", {"form":form, "profile":profile})

class DetailProfile(View):
	def get(self, request, *args, **kwargs):
		u = User.objects.filter(username=self.kwargs['username'])
		if u.exists():
			u = u[0]
			context = {}
			p = Profile.objects.get(user=u)
			sameUser = True if u.username == request.user.username else False
			gh = GitHubProfile.objects.filter(user=u)
			posts = Post.objects.filter(author=u)
			if gh.exists():
				context['github_profile'] = gh[0]
			context['profile'] = p
			context['sameUser'] = sameUser
			context['posts'] = posts
			if not sameUser:
				following = p.followers.filter(user=User.objects.get(username=self.request.user))
				following = following.exists()
				if following:
					res = "Following"
				else:
					res = "Follow"
				context['following'] = following
				context['follow_action_text'] = res	
			return render(request, "accounts/profile_detail.html", context)

def follow(request, *args, **kwargs):
	p = Profile.objects.filter(user=User.objects.get(username=kwargs['username']))
	# print(p)
	if p.exists():
		p = p[0]
		following = p.followers.filter(user=User.objects.get(username=request.user))
		following = following.exists()
		if following:
			p.followers.remove(p.followers.get(user=User.objects.get(username=request.user)))
			p.save()
		else:
			p.followers.add(Profile.objects.get(user=User.objects.get(username=request.user.username)))
			p.save()
		print(p.followers.all())
	return HttpResponse(request.user.username)

accounts/templates/accounts/profile_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% block title %} Create Profile {% endblock %} 
{% block body %}
<div id="page-content" class="wrapper users users-edit">
  <div
    class="crayons-layout crayons-layout--limited-l crayons-layout--1-col p-4"
  >
    <h1 class="crayons-title">Create Profile</h1>
    <form method="POST" enctype="multipart/form-data">
      <div class="crayons-card crayons-card--content-rows">
        <h2>User</h2>
        {% csrf_token %}
        <div class="crayons-field">
          {% if form.name.field.required %}
          <label for="{{i.id_for_label}}">{{form.name.name.capitalize}}*</label>
          {% else %}
          <label for="{{i.id_for_label}}">{{form.name.name.capitalize}}</label>
          {% endif %} {{form.name}}
        </div>
        <div class="crayons-field">
          {% if form.email.field.required %}
          <label for="{{i.id_for_label}}"
            >{{form.email.name.capitalize}}*</label
          >
          {% else %}
          <label for="{{i.id_for_label}}">{{form.email.name.capitalize}}</label>
          {% endif %} {{form.email}}
        </div>
        <div class="crayons-field">
          <label for="{{i.id_for_label}}">Profile Picture</label>
          <div class="flex items-center">
            <span class="crayons-avatar crayons-avatar--xl mr-2"
              ><img
			  	id="profile_preview"
                alt="{{profile.name}} profile image"
                src="{{profile.profile_picture.url}}"
                class="crayons-avatar__image"
            /></span>
			<input type="hidden" id="profile_base64" name="profile_base64"
			 value="">
            {{form.profile_picture}}
          </div>
          <p>&nbsp;</p>
          <p>{{form.errors}}</p>
        </div>
      </div>
      <div class="crayons-card crayons-card--content-rows">
        <h2>Basic</h2>
        <div class="crayons-field">
          {% if form.location.field.required %}
          <label for="{{i.id_for_label}}"
            >{{form.location.name.capitalize}}*</label
          >
          {% else %}
          <label for="{{i.id_for_label}}"
            >{{form.location.name.capitalize}}</label
          >
          {% endif %} {{form.location}}
        </div>
        <div class="crayons-field">
          {% if form.bio.field.required %}
          <label for="{{i.bio_for_label}}">{{form.bio.name.capitalize}}*</label>
          {% else %}
          <label for="{{i.id_for_label}}">{{form.bio.name.capitalize}}</label>
          {% endif %} {{form.bio}}
        </div>
        <div class="crayons-field">
          <label for="{{i.id_for_label}}">Website</label>
          {{form.website}}
        </div>
      </div>
      <div class="crayons-card crayons-card--content-rows">
        <h2>Links</h2>
        <div class="crayons-field">
          <label for="">GitLab URL</label>
          {{form.gitlab_url}}
          <label for="">Behance URL</label>
          {{form.behance_url}}
          <label for="">Instagram URL</label>
          {{form.instagram_url}}
          <label for="">GitHub URL</label>
          {{form.github_url}}
        </div>
      </div>
      <div class="crayons-card crayons-card--content-rows">
        <button type="submit" class="crayons-btn" style="width: 100%">
          Save Profile Information
        </button>
      </div>
    </form>
  </div>
</div>
<script>
  window.onload = function () {
    document.querySelector("#id_name").classList.add("crayons-textfield");
    document.querySelector("#id_email").classList.add("crayons-textfield");
    document.querySelector("#id_bio").classList.add("crayons-textfield");
    document.querySelector("#id_location").classList.add("crayons-textfield");
    document.querySelector("#id_bio").rows = 2;
    document.querySelector("#id_website").classList.add("crayons-textfield");
    document.querySelector("#id_gitlab_url").classList.add("crayons-textfield");
    document.querySelector("#id_github_url").classList.add("crayons-textfield");
    document.querySelector("#id_instagram_url").classList.add("crayons-textfield");
    document.querySelector("#id_behance_url").classList.add("crayons-textfield");
    const name = "{{profile.name}}";
    const bio = "{{profile.bio}}";
    const location = "{{profile.location}}";
    const email = "{{profile.email}}";
    const website = "{{profile.webiste}}";
    const profile_picture = "{{profile.profile_picture.url}}";
    const gitlab_url = "{{profile.gitlab_url}}";
    const github_url = "{{profile.github_url}}";
    const behance_url = "{{profile.behance_url}}";
    const instagram_url = "{{profile.instagram_url}}";
    document.querySelector("#id_name").value = name;
    document.querySelector("#id_email").value = email;
    document.querySelector("#id_bio").value = bio;
    document.querySelector("#id_location").value = location;
    document.querySelector("#id_website").value = website;
    document.querySelector("#id_gitlab_url").value = gitlab_url;
    document.querySelector("#id_github_url").value = github_url;
    document.querySelector("#id_instagram_url").value = instagram_url;
    document.querySelector("#id_behance_url").value = behance_url;
  };
  const profile_picture_i = document.getElementById("id_profile_picture");
  profile_picture_i.required = false 
  profile_picture_i.classList.add("crayons-card");
  profile_picture_i.classList.add("crayons-card--secondary");
  profile_picture_i.classList.add("p-3");
  profile_picture_i.classList.add("flex");
  profile_picture_i.classList.add("items-center");
  profile_picture_i.classList.add("flex-1");
  profile_picture_i.classList.add("w-100");
  // const class_list = ['crayons-card', ]
  profile_picture_i.onchange = function () {
    if (profile_picture_i.files && profile_picture_i.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        document.getElementById("profile_preview").src = e.target.result;
		document.getElementById('profile_base64').value = e.target.result;
	};
      reader.readAsDataURL(profile_picture_i.files[0]);
    }
  };
</script>
{% endblock %}

accounts/templates/accounts/update_profile_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% block title %} Update Profile {% endblock %} 
{% block body %}
<div id="page-content" class="wrapper users users-edit">
  <div
    class="crayons-layout crayons-layout--limited-l crayons-layout--1-col p-4"
  >
    <h1 class="crayons-title">Update Profile</h1>
    <form method="POST" enctype="multipart/form-data">
      <div class="crayons-card crayons-card--content-rows">
        <h2>User</h2>
        {% csrf_token %}
        <div class="crayons-field">
          {% if form.name.field.required %}
          <label for="{{i.id_for_label}}">{{form.name.name.capitalize}}*</label>
          {% else %}
          <label for="{{i.id_for_label}}">{{form.name.name.capitalize}}</label>
          {% endif %} {{form.name}}
        </div>
        <div class="crayons-field">
          {% if form.email.field.required %}
          <label for="{{i.id_for_label}}"
            >{{form.email.name.capitalize}}*</label
          >
          {% else %}
          <label for="{{i.id_for_label}}">{{form.email.name.capitalize}}</label>
          {% endif %} {{form.email}}
        </div>
        <div class="crayons-field">
          <label for="{{i.id_for_label}}">Profile Picture</label>
          <div class="flex items-center">
            <span class="crayons-avatar crayons-avatar--xl mr-2"
              ><img
			  	id="profile_preview"
                alt="{{profile.name}} profile image"
                src="{{profile.profile_picture.url}}"
                class="crayons-avatar__image"
            /></span>
			<input type="hidden" id="profile_base64" name="profile_base64"
			 value="">
            {{form.profile_picture}}
          </div>
          <p>&nbsp;</p>
          <p>{{form.errors}}</p>
        </div>
      </div>
      <div class="crayons-card crayons-card--content-rows">
        <h2>Basic</h2>
        <div class="crayons-field">
          {% if form.location.field.required %}
          <label for="{{i.id_for_label}}"
            >{{form.location.name.capitalize}}*</label
          >
          {% else %}
          <label for="{{i.id_for_label}}"
            >{{form.location.name.capitalize}}</label
          >
          {% endif %} {{form.location}}
        </div>
        <div class="crayons-field">
          {% if form.bio.field.required %}
          <label for="{{i.bio_for_label}}">{{form.bio.name.capitalize}}*</label>
          {% else %}
          <label for="{{i.id_for_label}}">{{form.bio.name.capitalize}}</label>
          {% endif %} {{form.bio}}
        </div>
        <div class="crayons-field">
          <label for="{{i.id_for_label}}">Website</label>
          {{form.website}}
        </div>
      </div>
      <div class="crayons-card crayons-card--content-rows">
        <h2>Links</h2>
        <div class="crayons-field">
          <label for="">GitLab URL</label>
          {{form.gitlab_url}}
          <label for="">Behance URL</label>
          {{form.behance_url}}
          <label for="">Instagram URL</label>
          {{form.instagram_url}}
          <label for="">GitHub URL</label>
          {{form.github_url}}
        </div>
      </div>
      <div class="crayons-card crayons-card--content-rows">
        <button type="submit" class="crayons-btn" style="width: 100%">
          Save Profile Information
        </button>
      </div>
    </form>
  </div>
</div>
<script>
  window.onload = function () {
    document.querySelector("#id_name").classList.add("crayons-textfield");
    document.querySelector("#id_email").classList.add("crayons-textfield");
    document.querySelector("#id_bio").classList.add("crayons-textfield");
    document.querySelector("#id_location").classList.add("crayons-textfield");
    document.querySelector("#id_bio").rows = 2;
    document.querySelector("#id_website").classList.add("crayons-textfield");
    document.querySelector("#id_gitlab_url").classList.add("crayons-textfield");
	document.querySelector("#id_gitlab_url").placeholder = "https://gitlab.com/...";
    document.querySelector("#id_github_url").classList.add("crayons-textfield");
    document.querySelector("#id_github_url").placeholder = "https://github.com/...";
    document.querySelector("#id_instagram_url").classList.add("crayons-textfield");
    document.querySelector("#id_instagram_url").placeholder = "https://instagram.com/...";
    document.querySelector("#id_behance_url").classList.add("crayons-textfield");
	document.querySelector('#id_behance_url').placeholder = "https://behance.net/..."
    const name = "{{profile.name}}";
    const bio = "{{profile.bio}}";
    const location = "{{profile.location}}";
    const email = "{{profile.email}}";
    const website = "{{profile.website}}";
    const profile_picture = "{{profile.profile_picture.url}}";
    const gitlab_url = "{{profile.gitlab_url}}";
    const github_url = "{{profile.github_url}}";
    const behance_url = "{{profile.behance_url}}";
    const instagram_url = "{{profile.instagram_url}}";
    document.querySelector("#id_name").value = name;
    document.querySelector("#id_email").value = email;
    document.querySelector("#id_bio").value = bio;
    document.querySelector("#id_location").value = location;
    document.querySelector("#id_website").value = website;
    document.querySelector("#id_gitlab_url").value = gitlab_url;
    document.querySelector("#id_github_url").value = github_url;
    document.querySelector("#id_instagram_url").value = instagram_url;
    document.querySelector("#id_behance_url").value = behance_url;
  };
  const profile_picture_i = document.getElementById("id_profile_picture");
  profile_picture_i.required = false 
  profile_picture_i.classList.add("crayons-card");
  profile_picture_i.classList.add("crayons-card--secondary");
  profile_picture_i.classList.add("p-3");
  profile_picture_i.classList.add("flex");
  profile_picture_i.classList.add("items-center");
  profile_picture_i.classList.add("flex-1");
  profile_picture_i.classList.add("w-100");
  // const class_list = ['crayons-card', ]
  profile_picture_i.onchange = function () {
    if (profile_picture_i.files && profile_picture_i.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        document.getElementById("profile_preview").src = e.target.result;
		document.getElementById('profile_base64').value = e.target.result;
	};
      reader.readAsDataURL(profile_picture_i.files[0]);
    }
  };
</script>
{% endblock %}